### ISSUE TITLE
[Android - build.gradle] targetSdkVersion should not be specified

### ISSUE THREAD

**Issue by sperochon** [RevenueCat/purchases-hybrid-common#183]
Hello,

I have a Flutter app that uses _purchases-flutter_ package (v3.10.0), and so indirectly imports _purchases-hybrid-common_ plugin package too (v1.11.2).
The _android/app/build.gradle_ of my app does not define **targetSdkVersion** at all. This is not mandatory. In such case, the default behavior is that **targetSdkVersion** is set internally to the same value than the one I have specify to **compileSdkVersion** except in one situation : when a lib specifies one (but should not).

The thing is that in your _purchases-hybrid-common_ package, you set a value to **targetSdkVersion** (inside [android/build.gradle](https://github.com/RevenueCat/purchases-hybrid-common/tree/main/android/build.gradle)). This value is 29(!) in v1.11.2. The gradle build process keep this value to override the **targetSdkVersion** of my app (since I have not specified any myself). Hopefully Google Play Store forbid me to publish an aab with **targetSdkVersion** 29 (too old).

Of course, I could specify a **targetSdkVersion** value inside the build.gradle of my app BUT :

A plugin package should not defines the **targetSdkVersion**. The Flutter default generator does not (https://docs.flutter.dev/development/packages-and-plugins/developing-packages#step-1-create-the-package-1)
And you can see any other (great) plugin available on pub.dev to check that they do not include **targetSdkVersion** too, for example:
https://github.com/googleads/googleads-mobile-flutter/blob/main/packages/google_mobile_ads/android/build.gradle
https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/android/build.gradle
...

[Edited]
And you don't do it neither in your own other package
https://github.com/RevenueCat/purchases-flutter/blob/main/android/build.gradle

Thanks.

Another tips: you should not specify **buildToolsVersion** neither.

**Comment by taquitos** [comment]
Whoopsie. Thank you for the report! We'll prioritize and get back to you!

**Comment by tonidero** [comment]
Hi @sperochon . We've investigated your proposal. `purchases-hybrid-common` contains an android library, not a flutter plugin, and `targetSdkVersion` is required in android libraries, otherwise the default behavior is to use the `minSdkVersion` as the default, see https://developer.android.com/guide/topics/manifest/uses-sdk-element. The wizard for new flutter apps also sets the `targetSdkVersion` to `flutter.targetSdkVersion` so we recommend you add it to your app so you have more control to indicate what version your app is tested on. 

As for the `buildToolsVersion`, it’s indeed not necessary in android libraries since the android gradle plugin 3.0 so we will consider removing it in future versions.

If you have any other questions or concerns, please reach back to us and we will try to help!

**Comment by sperochon** [comment]
Hi @tonidero , thanks for your feedback and your advices! 👍
